### ISSUE TITLE
坏了，3：30左右还能用，现在坏了

### ISSUE THREAD

**Issue by 360add** [mmxd12/nonebot_plugin_warframe_mode#3]
![Uploading QQ截图20230824155714.png…]()

**Comment by mmxd12** [comment]
有没有可能是框架原因？

**Comment by 360add** [comment]
![QQ截图20230824155714](https://github.com/mmxd12/nonebot_plugin_warframe_mode/assets/140232510/b7b9bd07-0b44-42c6-bbb2-87077a36f2b5)

**Comment by 360add** [comment]
08-24 16:01:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_warframe_mode)
08-24 16:01:37 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_warframe_mode) running complete
08-24 16:01:37 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_warframe_mode) failed.
Traceback (most recent call last):
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\anyio\_core\_tasks.py", line 119, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 184, in handle_async_request
    return await self._connection.handle_async_request(proxy_request)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\yld\BOT2\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_warframe_mode\__init__.py", line 423, in _
    message_rm = await rm_api(rm_url)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_warframe_mode\__init__.py", line 440, in rm_api
    res_rm = (await client.get(rm_url))
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

**Comment by mmxd12** [comment]
看出来了，稍后找个时间更新😂

**Comment by 360add** [comment]
![OYRFFJ4U9L _S%O)4ZAG2(R](https://github.com/mmxd12/nonebot_plugin_warframe_mode/assets/140232510/bf7f87fc-5990-42e2-b484-4009b457bac8)

**Comment by EiyoV** [comment]
修复了吗？还是失效了？我看服务器插件收到消息后已经运行了，但没有返回任何东西，还有个国服的插件试了试没问题

**Comment by mmxd12** [comment]
可能是接口失效最近被爆破了

**Comment by mmxd12** [comment]
框架原因，本来已经写好，但有框架测试了

**Comment by 360add** [comment]
这问题都好早的了，现在一直能正常用
