### ISSUE TITLE
打指令报错是为啥（刚刚接触插件）

### ISSUE THREAD

**Issue by kLogos** [mmxd12/nonebot_plugin_warframe_mode#6]
07-17 14:58:38 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_warframe_mode, lineno=26) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\lhcbot——by鼠鼠0401\lhcbot\src\plugins\nonebot_plugin_warframe_mode\__init__.py", line 107, in receive_voidTrader
    msg = await wfapi.voidTrader()
  File "C:\Users\Administrator\Desktop\lhcbot——by鼠鼠0401\lhcbot\src\plugins\nonebot_plugin_warframe_mode\data_source.py", line 208, in voidTrader
    image = text_on_image(data)
  File "C:\Users\Administrator\Desktop\lhcbot——by鼠鼠0401\lhcbot\src\plugins\nonebot_plugin_warframe_mode\data_source.py", line 89, in text_on_image
    text_width, text_height = draw.textsize(data, font) # type: ignore
AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by gblfday** [comment]
你的pillow太新了没有textsize这个函数，请使用9.5.0版本
我那个mmxd12账号登不上了你有问题可以进群

> pip install pillow==9.5.0

**Comment by gblfday** [comment]
有问题可以加群提问435021808感谢你的使用

**Comment by mmxd12** [comment]
你的pillow太新了没有textsize这个函数，请使用9.5.0版本
`pip install pillow==9.5.0`
